import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import * as vscode from "vscode";
import type { SSHHost } from "../core/types";
import { ensureUniqueSSHHostAlias } from "../core/sshAlias";
import { stringifyHosts } from "./sshConfig";

export const INTEGRATION_BEGIN = "# SSH Kit integration begin";
export const INTEGRATION_END = "# SSH Kit integration end";
export const MANAGED_INCLUDE = "Include ssh-kit/hosts.conf";

const LEGACY_ALIAS_PATTERN =
  /^# SSH Kit connect alias ([^\r\n]+) begin\r?\n[\s\S]*?^# SSH Kit connect alias \1 end\r?\n?/gm;

export interface ManagedIntegrationState {
  configPath: string;
  managedConfigPath: string;
  installed: boolean;
  effective: boolean;
  managed: boolean;
  legacyAliasCount: number;
}

export function getManagedConfigPath(): string {
  return path.join(os.homedir(), ".ssh", "ssh-kit", "hosts.conf");
}

export function getEffectiveSSHConfigPath(): string {
  const configured = vscode.workspace
    .getConfiguration("remote.SSH")
    .get<string>("configFile");
  return resolveLocalPath(configured || path.join(os.homedir(), ".ssh", "config"));
}

export function inspectManagedIntegration(
  configPath = getEffectiveSSHConfigPath()
): ManagedIntegrationState {
  const raw = fs.existsSync(configPath) ? fs.readFileSync(configPath, "utf8") : "";
  const managed = hasManagedIncludeBlock(raw);
  const installed = hasManagedInclude(raw);
  return {
    configPath,
    managedConfigPath: getManagedConfigPath(),
    installed,
    effective: installed && isManagedIncludeFirstDirective(raw),
    managed,
    legacyAliasCount: [...raw.matchAll(LEGACY_ALIAS_PATTERN)].length,
  };
}

export function regenerateManagedConfig(
  hosts: SSHHost[],
  managedPath = getManagedConfigPath()
): string {
  const aliases: string[] = [];
  const projected = hosts.map((host) => {
    const alias = ensureUniqueSSHHostAlias(
      host.sshAlias || host.name,
      host,
      aliases
    );
    aliases.push(alias);
    return { ...host, name: alias, sshAlias: alias };
  });
  const content = [
    "# This file is generated by SSH Kit. Manual changes will be overwritten.",
    "# Manage hosts in the SSH Kit view instead.",
    "",
    stringifyHosts(projected).trimEnd(),
    "",
  ].join("\n");
  atomicWriteText(managedPath, content, "\n");
  return managedPath;
}

export async function ensureManagedIntegration(hosts: SSHHost[]): Promise<boolean> {
  regenerateManagedConfig(hosts);
  const state = inspectManagedIntegration();
  if (state.installed && state.effective) {return true;}

  const setupAction = state.installed
    ? vscode.l10n.t("Repair integration")
    : vscode.l10n.t("Set up integration");
  const choice = await vscode.window.showWarningMessage(
    state.installed
      ? vscode.l10n.t("The SSH Kit Include in {path} appears after other SSH directives and may be overridden. Before repairing it, SSH Kit will save a copy of the current SSH Config so you can restore it if needed.", {
          path: state.configPath,
        })
      : vscode.l10n.t("SSH Kit needs to add an Include entry to {path} before Remote-SSH can use its managed hosts. Before changing the file, SSH Kit will save a copy that you can use to restore the original configuration. Other existing SSH settings will remain unchanged.", {
          path: state.configPath,
        }),
    { modal: true },
    setupAction
  );
  if (choice !== setupAction) {return false;}
  return state.installed
    ? repairManagedIntegration(hosts)
    : setupManagedIntegration(hosts);
}

export async function setupManagedIntegration(hosts: SSHHost[]): Promise<boolean> {
  regenerateManagedConfig(hosts);
  const state = inspectManagedIntegration();
  if (state.installed && state.effective) {return true;}
  if (state.installed) {return repairManagedIntegration(hosts);}

  const backupPath = await backupConfigBeforeIntegration(state.configPath);
  if (backupPath === null) {return false;}
  installManagedInclude(state.configPath);
  vscode.window.showInformationMessage(backupPath
    ? vscode.l10n.t("SSH Kit Remote-SSH integration is ready. Backup: {path}", { path: backupPath })
    : vscode.l10n.t("SSH Kit Remote-SSH integration is ready."));
  return true;
}

export async function repairManagedIntegration(hosts: SSHHost[]): Promise<boolean> {
  regenerateManagedConfig(hosts);
  const state = inspectManagedIntegration();
  if (state.installed && state.effective && !state.managed) {
    vscode.window.showInformationMessage(vscode.l10n.t(
      "Remote-SSH integration already uses the SSH Kit managed file through an unmarked Include. No changes were made."
    ));
    return true;
  }
  const backupPath = await backupConfigBeforeIntegration(state.configPath);
  if (backupPath === null) {return false;}
  if (state.managed) {
    removeManagedInclude(state.configPath);
  } else if (state.installed) {
    removeUnmarkedManagedIncludes(state.configPath);
  }
  installManagedInclude(state.configPath);
  vscode.window.showInformationMessage(backupPath
    ? vscode.l10n.t("SSH Kit Remote-SSH integration was repaired. Backup: {path}", { path: backupPath })
    : vscode.l10n.t("SSH Kit Remote-SSH integration was repaired."));
  return true;
}

export async function uninstallManagedIntegration(): Promise<boolean> {
  const state = inspectManagedIntegration();
  if (!state.installed) {return true;}
  if (!state.managed) {
    vscode.window.showInformationMessage(vscode.l10n.t(
      "The SSH Kit Include is not owned by SSH Kit, so it was left unchanged."
    ));
    return false;
  }
  const backupPath = await backupConfigBeforeIntegration(state.configPath);
  if (backupPath === null) {return false;}
  removeManagedInclude(state.configPath);
  vscode.window.showInformationMessage(vscode.l10n.t(
    "SSH Kit Remote-SSH integration was removed. SSH Kit data and managed hosts were kept."
  ));
  return true;
}

export async function cleanupLegacyAliasBlocks(
  configPath = getEffectiveSSHConfigPath()
): Promise<number | undefined> {
  if (!fs.existsSync(configPath)) {return 0;}
  const existing = fs.readFileSync(configPath, "utf8");
  const matches = [...existing.matchAll(LEGACY_ALIAS_PATTERN)];
  if (matches.length === 0) {return 0;}

  const backupPath = await backupConfigBeforeIntegration(configPath);
  if (backupPath === null) {return undefined;}
  const newline = detectNewline(existing);
  const updated = existing
    .replace(LEGACY_ALIAS_PATTERN, "")
    .replace(/\r?\n{3,}/g, `${newline}${newline}`);
  atomicWriteText(configPath, updated, newline);
  return matches.length;
}

export function installManagedInclude(configPath: string): void {
  const existing = fs.existsSync(configPath) ? fs.readFileSync(configPath, "utf8") : "";
  if (hasManagedInclude(existing)) {return;}
  const newline = detectNewline(existing);
  const bom = existing.startsWith("\uFEFF") ? "\uFEFF" : "";
  const body = bom ? existing.slice(1) : existing;
  const integration = [INTEGRATION_BEGIN, MANAGED_INCLUDE, INTEGRATION_END].join(newline);
  const updated = body.length > 0
    ? `${bom}${integration}${newline}${newline}${body}`
    : `${bom}${integration}${newline}`;
  atomicWriteText(configPath, updated, newline);
}

export function removeManagedInclude(configPath: string): void {
  if (!fs.existsSync(configPath)) {return;}
  const existing = fs.readFileSync(configPath, "utf8");
  const newline = detectNewline(existing);
  const bom = existing.startsWith("\uFEFF") ? "\uFEFF" : "";
  const body = bom ? existing.slice(1) : existing;
  const blockPattern = new RegExp(
    `^${escapeRegExp(INTEGRATION_BEGIN)}\\r?\\n${escapeRegExp(MANAGED_INCLUDE)}\\r?\\n${escapeRegExp(INTEGRATION_END)}\\r?\\n?`,
    "m"
  );
  const updatedBody = body
    .replace(blockPattern, "")
    .replace(/^\r?\n/, "");
  const updated = `${bom}${updatedBody}`;
  if (updated !== existing) {
    atomicWriteText(configPath, updated, newline);
  }
}

export function stripLegacyAliasBlocks(rawText: string): string {
  return rawText.replace(LEGACY_ALIAS_PATTERN, "");
}

function hasManagedInclude(rawText: string): boolean {
  if (hasManagedIncludeBlock(rawText)) {return true;}
  return rawText.split(/\r?\n/).some((line) =>
    line.trim().toLocaleLowerCase() === MANAGED_INCLUDE.toLocaleLowerCase()
  );
}

function hasManagedIncludeBlock(rawText: string): boolean {
  const markerPattern = new RegExp(
    `^${escapeRegExp(INTEGRATION_BEGIN)}\\r?\\n${escapeRegExp(MANAGED_INCLUDE)}\\r?\\n${escapeRegExp(INTEGRATION_END)}$`,
    "m"
  );
  return markerPattern.test(rawText.replace(/^\uFEFF/, ""));
}

function isManagedIncludeFirstDirective(rawText: string): boolean {
  const lines = rawText.replace(/^\uFEFF/, "").split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {continue;}
    return trimmed.toLocaleLowerCase() === MANAGED_INCLUDE.toLocaleLowerCase();
  }
  return false;
}

function removeUnmarkedManagedIncludes(configPath: string): void {
  if (!fs.existsSync(configPath)) {return;}
  const existing = fs.readFileSync(configPath, "utf8");
  const newline = detectNewline(existing);
  const lines = existing.split(/\r?\n/);
  const updated = lines
    .filter((line) => line.trim().toLocaleLowerCase() !== MANAGED_INCLUDE.toLocaleLowerCase())
    .join(newline);
  if (updated !== existing) {
    atomicWriteText(configPath, updated, newline);
  }
}

async function backupConfigBeforeIntegration(
  configPath: string
): Promise<string | null | undefined> {
  if (!fs.existsSync(configPath)) {return undefined;}
  const defaultName = `ssh-config-backup-${formatBackupTimestamp()}`;
  const uri = await vscode.window.showSaveDialog({
    title: vscode.l10n.t("Choose a file for this SSH Config backup"),
    defaultUri: vscode.Uri.file(path.join(os.homedir(), defaultName)),
    filters: {
      [vscode.l10n.t("SSH Config backup")]: ["conf", "txt", "bak"],
      [vscode.l10n.t("All files")]: ["*"],
    },
  });
  if (!uri) {return null;}

  const source = normalizeComparePath(configPath);
  const target = normalizeComparePath(uri.fsPath);
  if (source === target) {
    vscode.window.showErrorMessage(vscode.l10n.t("The backup location cannot be the SSH Config file itself."));
    return null;
  }
  try {
    if (fs.existsSync(uri.fsPath) && fs.statSync(uri.fsPath).isDirectory()) {
      vscode.window.showErrorMessage(vscode.l10n.t("Choose a backup file, not a folder."));
      return null;
    }

    const parentDirectory = path.dirname(uri.fsPath);
    if (!fs.existsSync(parentDirectory)) {
      fs.mkdirSync(parentDirectory, { recursive: true });
    }
    fs.copyFileSync(configPath, uri.fsPath);
  } catch (error) {
    vscode.window.showErrorMessage(vscode.l10n.t("Failed to save the SSH Config backup: {error}", {
      error: error instanceof Error ? error.message : String(error),
    }));
    return null;
  }
  return uri.fsPath;
}

function atomicWriteText(filePath: string, content: string, newline: string): void {
  const target = fs.existsSync(filePath) && fs.lstatSync(filePath).isSymbolicLink()
    ? fs.realpathSync(filePath)
    : filePath;
  const directory = path.dirname(target);
  fs.mkdirSync(directory, { recursive: true });
  const temp = path.join(directory, `.${path.basename(target)}.${process.pid}.${Date.now()}.tmp`);
  const normalized = content.replace(/\r?\n/g, newline);
  try {
    fs.writeFileSync(temp, normalized, {
      encoding: "utf8",
      mode: process.platform === "win32" ? undefined : 0o600,
    });
    fs.renameSync(temp, target);
  } finally {
    fs.rmSync(temp, { force: true });
  }
}

function resolveLocalPath(value: string): string {
  const expandedEnvironment = value
    .replace(/\$\{userHome\}/gi, os.homedir())
    .replace(/\$\{env:([^}]+)\}/gi, (_match, name: string) =>
      process.env[name] ?? ""
    );
  if (expandedEnvironment === "~") {return os.homedir();}
  if (expandedEnvironment.startsWith("~/") || expandedEnvironment.startsWith("~\\")) {
    return path.join(os.homedir(), expandedEnvironment.slice(2));
  }
  return path.resolve(expandedEnvironment);
}

function detectNewline(value: string): string {
  return value.includes("\r\n") ? "\r\n" : "\n";
}

function normalizeComparePath(value: string): string {
  const resolved = path.normalize(path.resolve(value));
  let normalized = resolved;
  try {
    normalized = fs.realpathSync.native(resolved);
  } catch {
    // A new backup path has no real path yet.
  }
  return process.platform === "win32" ? normalized.toLocaleLowerCase() : normalized;
}

function formatBackupTimestamp(): string {
  return new Date().toISOString().replace(/[:.]/g, "-");
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
